// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // if (kIsWeb) {
    //   return web;
    // }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyDuvQcyUFddnVJsworsw1M0V9dYCA3U2fI',
  //   appId: '1:385959227937:web:ae75bbf59311391f70e960',
  //   messagingSenderId: '385959227937',
  //   projectId: 'digitaldatatreeglobal',
  //   authDomain: 'digitaldatatreeglobal.firebaseapp.com',
  //   storageBucket: 'digitaldatatreeglobal.appspot.com',
  //   measurementId: 'G-EG2R1271VF',
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyxAxSiLjFCvZQmAWvBR4qvYmdxErk_HA',
    appId: '1:385959227937:android:76a9b3b64d26a3e670e960',
    messagingSenderId: '385959227937',
    projectId: 'digitaldatatreeglobal',
    storageBucket: 'digitaldatatreeglobal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvPqRBiquec6i7MRtZJO5jDeJf3aQMoR0',
    appId: '1:385959227937:ios:0ce463342a24be0570e960',
    messagingSenderId: '385959227937',
    projectId: 'digitaldatatreeglobal',
    storageBucket: 'digitaldatatreeglobal.appspot.com',
    iosClientId:
        '385959227937-3luqq2h5pc8dl4nero824ijg3nqksqgt.apps.googleusercontent.com',
    iosBundleId: 'com.example.digitalDataTree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvPqRBiquec6i7MRtZJO5jDeJf3aQMoR0',
    appId: '1:385959227937:ios:0ce463342a24be0570e960',
    messagingSenderId: '385959227937',
    projectId: 'digitaldatatreeglobal',
    storageBucket: 'digitaldatatreeglobal.appspot.com',
    iosClientId:
        '385959227937-3luqq2h5pc8dl4nero824ijg3nqksqgt.apps.googleusercontent.com',
    iosBundleId: 'com.example.digitalDataTree',
  );
}
